version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    groups:
      all-dependencies:
        patterns:
          - '*'
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
